SUPPORTED_BASIC_CALCULATOR_OPERATIONS = {
    'adding',
    'subtraction',
    'square',
    'square_root',
}
SUPPORTED_ADVANCED_CALCULATOR_OPERATIONS = {
    'bin_log',
    'nat_log',
}

SUPPORTED_OPERATIONS = SUPPORTED_BASIC_CALCULATOR_OPERATIONS.union(SUPPORTED_ADVANCED_CALCULATOR_OPERATIONS)
